"""add machine_name to errors

Revision ID: 140e2cb998cc
Revises: 2ec9b2da1b80
Create Date: 2026-09-18 23:12:37.472860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140e2cb998cc'
down_revision = '2ec9b2da1b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_name', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_errors_machine_name'), ['machine_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_machine_name'))
        batch_op.drop_column('machine_name')

    # ### end Alembic commands ###
