"""V1.2 initial schema

Revision ID: 4fa4b0e088fb
Revises: 
Create Date: 2026-09-17 23:54:29.300630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa4b0e088fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=False),
    sa.Column('error_name', sa.String(length=200), nullable=False),
    sa.Column('error_fix', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_errors_error_code'), ['error_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_errors_error_name'), ['error_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_errors_status'), ['status'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_code', sa.String(length=20), nullable=False),
    sa.Column('shop_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_shop_code'), ['shop_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shops_status'), ['status'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=160), nullable=False),
    sa.Column('machine_code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'machine_code', name='uq_machine_shop_code')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_machine_code'), ['machine_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_machine_name'), ['machine_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('machine_errors',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('machine_id', 'error_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_errors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_shop_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_status'))
        batch_op.drop_index(batch_op.f('ix_machines_shop_id'))
        batch_op.drop_index(batch_op.f('ix_machines_machine_name'))
        batch_op.drop_index(batch_op.f('ix_machines_machine_code'))

    op.drop_table('machines')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_status'))
        batch_op.drop_index(batch_op.f('ix_shops_shop_code'))

    op.drop_table('shops')
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_status'))
        batch_op.drop_index(batch_op.f('ix_errors_error_name'))
        batch_op.drop_index(batch_op.f('ix_errors_error_code'))

    op.drop_table('errors')
    # ### end Alembic commands ###
