"""V2 add error_images table

Revision ID: 54629352936c
Revises: 4fa4b0e088fb
Create Date: 2026-09-18 12:27:13.488495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54629352936c'
down_revision = '4fa4b0e088fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_images_error_id'), ['error_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_images_error_id'))

    op.drop_table('error_images')
    # ### end Alembic commands ###
