"""V5.2 add error category

Revision ID: b894e7e793d6
Revises: 551af63996e4
Create Date: 2026-09-18 18:37:15.283824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b894e7e793d6'
down_revision = '551af63996e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False, server_default='ERROR'))
        batch_op.create_index(batch_op.f('ix_errors_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
