"""V3 add sync_states and change_logs tables

Revision ID: d9e8950b1337
Revises: 54629352936c
Create Date: 2026-09-18 14:02:32.239734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e8950b1337'
down_revision = '54629352936c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_logs_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_logs_version'), ['version'], unique=False)
        batch_op.create_index('ix_changelog_entity_version', ['entity', 'version'], unique=False)

    op.create_table('sync_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_states_entity'), ['entity'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_states_entity'))

    op.drop_table('sync_states')
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_changelog_entity_version')
        batch_op.drop_index(batch_op.f('ix_change_logs_version'))
        batch_op.drop_index(batch_op.f('ix_change_logs_record_id'))
        batch_op.drop_index(batch_op.f('ix_change_logs_entity'))

    op.drop_table('change_logs')
    # ### end Alembic commands ###
